/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zch_atguigu_jniutils_JavaCallC */

#ifndef _Included_com_zch_atguigu_jniutils_JavaCallC
#define _Included_com_zch_atguigu_jniutils_JavaCallC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zch_atguigu_jniutils_JavaCallC
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zch_atguigu_jniutils_JavaCallC_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_zch_atguigu_jniutils_JavaCallC
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zch_atguigu_jniutils_JavaCallC_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zch_atguigu_jniutils_JavaCallC
 * Method:    increaseArrayEles
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_zch_atguigu_jniutils_JavaCallC_increaseArrayEles
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_zch_atguigu_jniutils_JavaCallC
 * Method:    checkPwd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zch_atguigu_jniutils_JavaCallC_checkPwd
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
